version: '3'

services:
  app:
    build: .
    tty: true
    ports:
      - 3000:3000
      - 5555:5555
    volumes:
      - .:/app
      - node_modules-volume:/app/node_modules
    depends_on:
      - db
  db:
    build:
      context: '.'
      dockerfile: 'db.Dockerfile'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: para-feed-reader
volumes:
  node_modules-volume:
